/*
 * ─────────────────────────────────────────────────────────────────────────────
 *  MULTIQC  —  Aggregate QC report across all samples
 *
 *  Collects FastQC, fastp, STAR, featureCounts, RSeQC, and samtools outputs.
 *
 *  Outputs:
 *    report : multiqc_report.html
 *    data   : multiqc_data/ directory (JSON, TSV tables)
 * ─────────────────────────────────────────────────────────────────────────────
 */
process MULTIQC {
    label 'process_low'
    publishDir "${params.outdir}/MultiQC", mode: params.publish_dir_mode

    input:
    path(qc_files)

    output:
    path "multiqc_report.html",  emit: report
    path "multiqc_data",         emit: data

    script:
    """
    multiqc . \\
        --title "Roche_nxt RNAseq QC Report" \\
        --comment "Generated by Roche_nxt RNAseq pipeline" \\
        --force
    """
}
